### PR TITLE
Fix vitest reporters with options

### LINKED ISSUE #921: 🐛 Vitest plugin doesn't handle reporters with options
### Prerequisites

- [x] I'm using the latest version
- [x] I've read the relevant [documentation](https://knip.dev)
- [x] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [x] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [x] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://github.com/dakro/knip-issues/tree/vitest-reporters

### Reproduction access

- [x] I've made sure the reproduction is publicly accessible

### Description of the issue

Vitest reporters can be in the form:
`['reporter-name', {options:{}}]`

Knip reports unused 'reporter-name' dependency in this case

### PR DESCRIPTION
**Pull request by dakro**
Fix #921

### CODE REVIEW

File: packages/knip/src/plugins/vitest/helpers.ts [hunk 1]
```diff
@@ -44,6 +44,7 @@ const builtInReporters = [
 export const getExternalReporters = (reporters?: ViteConfig['test']['reporters']) =>
   reporters
     ? [reporters]
+        .flat()
         .flat()
         .filter((reporter): reporter is string => typeof reporter === 'string' && !builtInReporters.includes(reporter))
```
Comment (webpro) [inline packages/knip/src/plugins/vitest/helpers.ts:49]: Extra flattening may lead to unexpected reporters maybe if there's a string "anywhere"? How about instead of the extra `flat()` perhaps it would make sense to return `reporter` if it's a string or `reporter[0]` for an array (or ignore otherwise)?

File: packages/knip/test/plugins/vitest7.test.ts [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+
+  assert(issues.unlisted['vitest.config.ts']['ReporterString']);
+  assert(issues.unlisted['vitest.config.ts']['ReporterArray']);
+
+  assert.deepEqual(counters, {
+    ...baseCounters,
+    files: 0,
+    processed: 3,
+    total: 3,
+    unlisted: 2,
```
Comment (webpro) [inline packages/knip/test/plugins/vitest7.test.ts:24]: This is fine, yet ideally we'd add `ReporterString` and `ReporterArray` to dependencies in `package.json` so they'll be both listed and referenced, and there should be no issues left here in the test ("full circle").

**Review by webpro — COMMENTED** [review]
Thanks! Happy to merge, but two remarks I have.

File: packages/knip/src/plugins/vitest/helpers.ts (hunk 1 above)
Comment (dakro) [reply packages/knip/src/plugins/vitest/helpers.ts:49]: Yes, at the moment should not be possible to have a string, but in this way will be more future proof, I will change as suggested

File: packages/knip/test/plugins/vitest7.test.ts (hunk 2 above)
Comment (dakro) [reply packages/knip/test/plugins/vitest7.test.ts:24]: Do you prefer just to change this test or to add another one?

Comment (webpro) [reply packages/knip/test/plugins/vitest7.test.ts:24]: This one test should be enough!

**Comment by webpro** [comment]
Thanks @dakro! Great stuff.

**Comment by webpro** [comment]
:rocket: _This pull request is included in v5.42.3. See [Release 5.42.3](https://github.com/webpro-nl/knip/releases/tag/5.42.3) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._
