### PR TITLE
fix(plugin): swc with `externalHelpers` setting ignores `@swc/helpers` dependency

### LINKED ISSUE #1555: 🐛 `swc` with `externalHelpers` config marked `@swc/helpers` as "unused dependency"
### Prerequisites

- [x] I'm using the latest version
- [x] I've read the relevant [documentation](https://knip.dev)
- [x] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [x] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [x] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

https://stackblitz.com/edit/github-qdqksz8w

### Reproduction access

- [x] I've made sure the reproduction is publicly accessible

### Description of the issue

SWC has a setting to use a dependency for generated helper code:

https://swc.rs/docs/configuration/compilation#jscexternalhelpers

When this setting is enabled, you have to add the dependency `@swc/helpers`. Knip recognize this dependency as unused.

TypeScript also does have this kind of setting, and it's already handled by Knip:

https://github.com/webpro-nl/knip/blob/58674ade551d04ca38eea5b8273e8843eed7659d/packages/knip/src/plugins/typescript/index.ts#L41

See TypeScript docs: https://www.typescriptlang.org/tsconfig/#importHelpers

### PR DESCRIPTION
**Pull request by bobaaaaa**
Fixes #1555

### CODE REVIEW

File: packages/knip/src/plugins/swc/index.ts [hunk 1]
```diff
@@ -16,7 +17,8 @@ const config: string[] = ['.swcrc'];
 
 const resolveConfig: ResolveConfig<SWCConfig> = async config => {
   const inputs = config?.jsc?.experimental?.plugins ?? [];
-  return inputs.map(([id]) => toDependency(id));
+  const externalHelpers = config.jsc?.externalHelpers ? ['@swc/helpers'] : [];
+  return compact([...inputs.map(([id]) => toDependency(id)), ...externalHelpers.map(id => toDependency(id))]);
```
Comment (webpro) [inline packages/knip/src/plugins/swc/index.ts]:
```suggestion
  return compact([...inputs, ...externalHelpers]).map(id => toDependency(id));
```

**Review by webpro — COMMENTED** [review]
Thanks Patrick! Happy to merge, just one nit.

File: packages/knip/src/plugins/swc/index.ts (hunk 1 above)
Comment (bobaaaaa) [reply packages/knip/src/plugins/swc/index.ts]: I have simplified the line, but keep in mind that `inputs` does have a different type than `externalHelpers`: `Array<[pluginName: string, pluginOptions: Record<string, unknown>]>;` vs `Array<string>`

Comment (webpro) [reply packages/knip/src/plugins/swc/index.ts]: Hmm in that case any chance you could fix that up properly as well then? I was merely responding to the change at hand and `compact` only dedupes primitives.

Comment (bobaaaaa) [reply packages/knip/src/plugins/swc/index.ts]: I can not change this, because this is given by the swc config itself

Comment (webpro) [reply packages/knip/src/plugins/swc/index.ts]: Thank you!

**Comment by webpro** [comment]
:rocket: _This pull request is included in v5.86.0. See [Release 5.86.0](https://github.com/webpro-nl/knip/releases/tag/knip%405.86.0) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._
