### PR TITLE
Fix Yarn (Berry) plugins and binaries reported as unused

### LINKED ISSUE #1505: 🔄 [5.83.0] False positive for .yarn
### Prerequisites

- [x] I've read the relevant [documentation](https://knip.dev)
- [x] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [x] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

TODO

### Reproduction access

- [x] I've made sure the reproduction is publicly accessible

### Good version

5.82.1

### Bad version

5.83.0

### Description of the regression

Files in the `.yarn` folder are marked as "unused files". 

This includes yarn releases installed in `.yarn/releases` if `yarnPath` is set (see [docs](https://yarnpkg.com/configuration/yarnrc#yarnPath) ) and plugins installed in `.yarn/plugins` with `yarn plugin import`. 
Additionally, if a plugin is called in the package.json scripts, it will be flagged under "unlisted binaries" 

I'll work on a minimal repro once stackblitz behaves, or I'll try to find the related commit, whichever comes first

### LINKED ISSUE #1522: 🐛 Yarn (Berry) plugins reported as unused
### Prerequisites

- [x] I'm using the latest version
- [x] I've read the relevant [documentation](https://knip.dev)
- [x] I've searched for [existing issues](https://github.com/webpro-nl/knip/issues?q=is%3Aissue)
- [x] I've checked the [list of known issues](https://knip.dev/reference/known-issues)
- [x] I've read the [issue reproduction guide](https://knip.dev/guides/issue-reproduction)

### Reproduction url

No control over package manager in codesandbox; see description below

### Reproduction access

- [x] I've made sure the reproduction is publicly accessible

### Description of the issue

Considering the following Yarn (Berry) configuration:

`.yarnrc.yml`
```yml
plugins:
  - checksum: …
    path: .yarn/plugins/@yarnpkg/plugin-nolyfill.cjs
    spec: "https://…/@yarnpkg/plugin-nolyfill.js"
```

`.yarn/plugins/@yarnpkg/plugin-nolyfill.cjs` should not be reported as unused.

### PR DESCRIPTION
**Pull request by wojtekmaj**
Fixes #1505
Fixes #1522

Closes #1509

This PR adds support for `plugins` and `yarnPath` that may be referenced in `.yarnrc.yml`. Thanks to this change, we no longer raise a false positive for `.yarn/*` while also avoiding false _negatives_ that #1509 would have introduced by completely ignoring `.yarn` directory.

> [!NOTE]
> This PR was created with AI assistance (GPT 5.3 Codex).

### CODE REVIEW

**Comment by wojtekmaj** [comment]
@webpro Is there anything else I can do to get this merged? Or you're happy with it?

File: packages/knip/src/plugins/yarn/index.ts [hunk 1]
```diff
@@ -11,14 +13,38 @@ const isEnabled: IsPluginEnabled = async ({ cwd }) => isFile(cwd, 'yarn.lock');
...
 const entry = ['yarn.config.cjs'];
 
+type YarnConfig = {
+  plugins?: Array<{
+    path?: string;
+  }>;
+};
+
+const resolveConfig: ResolveConfig<YarnConfig> = (localConfig, options) => {
+  const inputs: Input[] = [toDeferResolveEntry('yarn.config.cjs', { containingFilePath: options.configFilePath })];
```
Comment (webpro) [inline packages/knip/src/plugins/yarn/index.ts]: Not sure why `'yarn.config.cjs` is added here, it's already an `entry` item. I think we should remove it.

File: packages/knip/src/plugins/yarn/index.ts [hunk 2]
```diff
@@ -11,14 +13,38 @@ const isEnabled: IsPluginEnabled = async ({ cwd }) => isFile(cwd, 'yarn.lock');
...
+  if (!Array.isArray(localConfig.plugins)) return inputs;
+
+  for (const plugin of localConfig.plugins) {
+    if (typeof plugin.path !== 'string') continue;
+    inputs.push(
+      toDeferResolveEntry(plugin.path, { dir: options.configFileDir, containingFilePath: options.configFilePath })
+    );
```
Comment (webpro) [inline packages/knip/src/plugins/yarn/index.ts]:
```suggestion
    inputs.push(toEntry(plugin.path));
```

File: packages/knip/test/plugins/yarn2.test.ts [hunk 3]
```diff
@@ -5,19 +5,16 @@ import baseCounters from '../helpers/baseCounters.js';
...
+const cwd = resolve('fixtures/plugins/yarn-berry');
 
-test('Ignore unresolved issues for Metro defaults', async () => {
+test('Find dependencies with the yarn plugin (Berry)', async () => {
   const options = await createOptions({ cwd });
   const { issues, counters } = await main(options);
 
-  assert(issues.dependencies['package.json']['react']);
-  assert(issues.dependencies['package.json']['react-native']);
+  assert(issues.files.size === 0);
```
Comment (webpro) [inline packages/knip/test/plugins/yarn2.test.ts]:
```suggestion
```

**Review by webpro — COMMENTED** [review]
Thanks for the PR. Has all the red flags to basically ignore it, though. Using AI is your responsibility, not mine. I could do without the overhead it's causing: https://github.com/webpro-nl/knip/blob/main/.github/DEVELOPMENT.md#agents. Some might feel I'm exaggerating here, but even a rather small PR like this isn't a joy to review to begin with.

But after all, what matters most I guess, is the intention here is fine. We can get this merged.

File: packages/knip/src/plugins/yarn/index.ts (hunk 1 above)
Comment (wojtekmaj) [reply packages/knip/src/plugins/yarn/index.ts]: When I removed it, issues.files counter went up. At the time I thought that's bad. :D

File: packages/knip/src/plugins/yarn/index.ts (hunk 2 above)
Comment (wojtekmaj) [reply packages/knip/src/plugins/yarn/index.ts]: Done :)

File: packages/knip/test/plugins/yarn2.test.ts (hunk 3 above)
Comment (wojtekmaj) [reply packages/knip/test/plugins/yarn2.test.ts]: Replaced it with extra assertion ensuring plugin's not there.

**Comment by wojtekmaj** [comment]
> Some might feel I'm exaggerating here, but even a rather small PR like this isn't a joy to review to begin with.

I don't think you're exaggerating at all and you have full right to this stance. 

> I could do without the overhead it's causing: https://github.com/webpro-nl/knip/blob/main/.github/DEVELOPMENT.md#agents. 

That was my first encounter with Knip's codebase and I was hoping handwritten fixtures, AGENTS.md and full transparency on where the slop is would give somewhat satisfactory results, I guess I was wrong, sorry about that 😅 Hope this PR is in better shape now!

File: packages/knip/src/plugins/yarn/index.ts (hunk 1 above)
Comment (webpro) [reply packages/knip/src/plugins/yarn/index.ts]: Apologies, I was wrong here. Got confused by `yarn.config.cjs` that should not be hardcoded. Yet `config` patterns are automatically added as `entry` files. However, indeed we should both include `entry` with the default plugin export (for generated docs to show defaults), and include it in the inputs we return from `resolveConfig` (so that we have a chance to override if necessary). I'll push a fix.

**Comment by webpro** [comment]
> > Some might feel I'm exaggerating here, but even a rather small PR like this isn't a joy to review to begin with.
> 
> I don't think you're exaggerating at all and you have full right to this stance.
> 
> > I could do without the overhead it's causing: https://github.com/webpro-nl/knip/blob/main/.github/DEVELOPMENT.md#agents.
> 
> That was my first encounter with Knip's codebase and I was hoping handwritten fixtures, AGENTS.md and full transparency on where the slop is would give somewhat satisfactory results, I guess I was wrong, sorry about that 😅 Hope this PR is in better shape now!

No worries at all. New territory for me as well, learning a lot from this. Thanks for bearing with me!

**Comment by webpro** [comment]
:rocket: _This pull request is included in v5.84.0. See [Release 5.84.0](https://github.com/webpro-nl/knip/releases/tag/knip%405.84.0) for release notes._

_Using Knip in a commercial project? Please consider [becoming a sponsor](https://knip.dev/sponsors)._
